### ISSUE TITLE
Forest: Clicking *Vision Link* then *Back* persists in-game error message

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#102]
In the journal, click *Vision Link* then click *Back*.

The "Remote Link Temporarily Unavailable" message is still displayed. It should have disappeared when *Back* was clicked.

The errant message will go away if you click on it. Until then, input is blocked.

(works correctly in retail game)

![vision-link](https://user-images.githubusercontent.com/1754130/171970736-26eb3710-0316-49b9-8304-66d1e343c9d0.png)

**Comment by rparnas** [comment]
A similar test case that fails as of dcb19fbfbbf50c08f793c4fef1bac3eaf225f5cd
- Go to the 'Projects'
- Press the right arrow on the 'Rotate' control on the top-right of the Journal to go to 'Vision Link'
- The in-game error message appears in the Journal.
- Keep clicking the right arrow on the 'Rotate' control until you reach 'Mail'
- The error should go away on its own upon reaching 'Mail' (currently it is still there)

**Comment by elasota** [comment]
Fixed by 7ac9be5cfdb4c188318b29c1e287ccc4e32a558b
