### ISSUE TITLE
Bureau: Issues with replaying videos that have already played once.

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#103]
1. At "Information", ring the bell.
2. Ring the bell again. The vidbot says "Look, I'm trying to read here, okay?..."
3. Ring the bell a third time. The vidbot freezes.
4. If you leave the screen and come back, pressing the bell again will play the correct video clip (once).

In retail, the second video clip repeats each time you press the bell again.

**Comment by rparnas** [comment]
At "Hints" there are three hint prompts and three hint responses for Yes (plus one response for No).

After the third hint prompt (about Max), when you click "Yes" the response video does not play.

Eventually it plays the "done talking" SFX and you can click again. The Hints bot then sometimes plays videos correctly and sometimes skips playing them, though you can continue to interact with it.

**Comment by rparnas** [comment]
At the desk who says "Bring me the blue pages" there are three videos.

Keep clicking and when it gets back to the first one it fails to play.

See also: "Bridge Repair", "Travel", "Reception".

**Comment by rparnas** [comment]
Once the cloud ring puzzle is complete, the animation of a cloud raining is supposed to loop continuously without gaps.

**Comment by elasota** [comment]
Looping QuickTime movies is broken, #53 is the same problem, and the Inspiration propulsion room movie doesn't loop either.

**Comment by elasota** [comment]
The information desk one is fixed, but the Sources (Myst book/blue pages) one is still not playing the first video correctly.

**Comment by elasota** [comment]
Remainder should be fixed by adc9211b1ff5a4922c15da6fc8014ead3b1bc10c
