### ISSUE TITLE
Bureau: word mixer-game is case-sensitive for player guesses

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#119]
The word mixer-game is case-sensitive for player guesses. This causes the player to misunderstand how the game works or give up before seeing the clue. Inconsistently, when the CPU outputs a guess, I think these are always lowercase regardless of initial input.

1. Enter the words 'Standard Damage' as the words to mix.
2. Enter longest word 'stem'
3. Terminal says 'That doesn't use the letters in [Standard Damage]'

I suggest truncating all inputs to word mixer to lowercase.

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS- Fix paused videos taking a long time to unpause. · elasota-scummvm@d8886e4](https://github.com/elasota/scummvm/commit/d8886e475b3d93d045eda915061a095ffb0fbd41)

**Comment by elasota** [comment]
This was actually supposed to be addressed in the WordMixer modifier, but apparently the scripts were also using TextWork to check for characters, and TextWork is case-sensitive.  Fixed by 1674e8722b91aefb7af48a59b8bfeab78a6d0873.
