### ISSUE TITLE
Bureau: Vidbots begin/end sound is quiet

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#132]
The sound effects when vidbots begin/end a voice clip (glitchy ascending notes sound) seems much quieter in ScummVM.

Tested against (and ensured options was set to Sound=10, Music=10):
* Win retail on Win98 SE
* [MTROPOLIS: Add auto-save triggers for Obsidian Immediate Action clock… · elasota/scummvm@dcb19fb](https://github.com/elasota/scummvm/commit/dcb19fbfbbf50c08f793c4fef1bac3eaf225f5cd)

**Comment by elasota** [comment]
The sound effect is actually a MIDI file.  I checked that the volume levels that it's being set to are sensible but something is still obviously fishy.

**Comment by elasota** [comment]
Fixed by d91ea819efdfb358f67726ecf21b5c5f7cb50d6c and b8dfa656778207c3d44b30bdd4bfc2c8ddb66718
