### ISSUE TITLE
Bureau: Clickable area for rearranging cloud ring letters is incorrect

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#134]
In SCUMMVM, Once a letter is placed in a slot for the cloud ring puzzle, the clickable/draggable area is not correct. (Letters can still be dragged by clicking in the black space near the letter, meaning there are no deadlocks).

**Incorrect**
![cloud-ring-scummvm](https://user-images.githubusercontent.com/1754130/177070586-bee96e41-ce2f-4590-b993-aaf790a127ab.png)

**Correct**
![cloud-ring-win98](https://user-images.githubusercontent.com/1754130/177070660-b2f9662f-cf77-414a-a162-67edf3d5a821.jpg)

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS: Add auto-save triggers for Obsidian Immediate Action clock… · elasota/scummvm@dcb19fb](https://github.com/elasota/scummvm/commit/dcb19fbfbbf50c08f793c4fef1bac3eaf225f5cd)

**Comment by elasota** [comment]
Fixed by 87aacc623b751d5b186dd2a32f0976c7231d7097
