### ISSUE TITLE
Spider: The animation for the metal lever flips some textures

### ISSUE THREAD

**Issue by rparnas** [elasota/scummvm#137]
Unfixable movie asset issue, I assume.

**Before Animation**
![before-animation](https://user-images.githubusercontent.com/1754130/177467656-21479224-7eb8-49eb-8711-b234e59ff9db.png)

**During Animation**
![after-animation](https://user-images.githubusercontent.com/1754130/177467553-9b62bf28-25db-4840-9bcd-62741ecbc794.png)

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS: Fix incorrect mToon mouse collision frame offset handling · elasota/scummvm@87aacc6](https://github.com/elasota/scummvm/commit/87aacc623b751d5b186dd2a32f0976c7231d7097)

**Comment by elasota** [comment]
Can't really do anything about this.
