### ISSUE TITLE
Bureau: Cube maze contents need to be tested

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#14]
Test task.  Need to test the vidbots/interactables in the cube maze

**Comment by elasota** [comment]
Solutions for testing attempted entry into the middle room without enough cards to leave it:
Assuming grid:
0 1 2
3 4 5
6 7 8

Stuck from north room: 1-> 4
Stuck from west room: 2 -> 5 -> 4 -> 7 -> 8 -> 5 -> 4 -> 3 -> 4
Stuck from south room: 7 -> 4 -> 5 -> 2 -> 5 -> 4 -> 7 -> 4

**Comment by rparnas** [comment]
- Tested all cube maze contents, including visiting pre-approvals with and without the needed form. Only issue found was #133.
- "Stuck from north room" path does not cause player to be stuck. The two other stuck paths listed worked correctly.

Tested against:
* [MTROPOLIS: Add auto-save triggers for Obsidian Immediate Action clock… · elasota/scummvm@dcb19fb](https://github.com/elasota/scummvm/commit/dcb19fbfbbf50c08f793c4fef1bac3eaf225f5cd)
