### ISSUE TITLE
Spider: Test side interactables

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#30]
Testing task: Go to each side area and test interactables

**Comment by rparnas** [comment]
Tested all of Spider including re-entering areas for completed puzzles. Only found #138 and #139.

Did I miss any interactable?

**Interactables:**
- North
  - (nothing, except exit from constellation room)
- East
  - giant bellows
- South
  - giant ladle of molten iron
- West
  - furnace
  - gondola to control panel of levers --> four levels
- Center
  - grate where you can see max
  - hand wheel with hook that attaches to grate
- Metal Area
  - Conveyor start button
  - Conveyor jar holder
  - Chem set in chem lab
  - VCR in chem lab
- Fire Area
  - tree & sun
- Air Area
  - canon
  - canon matrix setting
- Oil Area
  - waves
  - oil extractor
  - castle slide puzzle
  - castle map display with hand wheels
- Constellation Room
  - slots
  - connect-the-dots

Tested against:
* Win retail on Win98 SE
* [MTROPOLIS: Fix incorrect mToon mouse collision frame offset handling · elasota/scummvm@87aacc6](https://github.com/elasota/scummvm/commit/87aacc623b751d5b186dd2a32f0976c7231d7097)

**Comment by elasota** [comment]
This task was just for the "main" area, not the puzzles, but sounds like it's done.
