### ISSUE TITLE
Inspiration: Test Church side areas and hints

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#62]

**Comment by rparnas** [comment]
No issues found. 

Tested Church of the Machine by walking around before and after puzzle completion (including going to another location and returning).

Only interactable other than the Spider seems to be Bismuth (who shows you his book). The book has one hint at the beginning and another if you return later on. If there's a third hint in the book, I didn't see it.

Tested against:
* Win retail on Win98 SE
* [SCUMM: (LOOM/EGA) - fix bug 13763 (Inaccurate text position) · scummvm/scummvm@b4185bd](https://github.com/scummvm/scummvm/commit/b4185bdf60f8f28afe57b192f7073135e0eb2cc8)
