### ISSUE TITLE
Inspiration: Test incorrect Robot paths in Church

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#64]

**Comment by rparnas** [comment]
No issues found, testing including "crash" and "chip gets wiped" failure conditions.

Up to you if more testing is needed given the thousands of possibilities.

Tested against:
* Win retail on Win98 SE
* [SCUMM: (LOOM/EGA) - fix bug 13763 (Inaccurate text position) · scummvm/scummvm@b4185bd](https://github.com/scummvm/scummvm/commit/b4185bdf60f8f28afe57b192f7073135e0eb2cc8)
