### ISSUE TITLE
Inspiration: Test Statue gallery side areas

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#66]

**Comment by rparnas** [comment]
No issues found.

* Looked at concept art
* Pressed commentary buttons (before and after puzzle completion)
* Gave bismuth preset canvases using yellow button on press

Tested against:
* Win retail on Win98 SE
* [SCUMM: (LOOM/EGA) - fix bug 13763 (Inaccurate text position) · scummvm/scummvm@b4185bd](https://github.com/scummvm/scummvm/commit/b4185bdf60f8f28afe57b192f7073135e0eb2cc8)
