### ISSUE TITLE
Global: Check usage of boundary detection modifier

### ISSUE THREAD

**Issue by elasota** [elasota/scummvm#96]
This modifier is present in some scenes, needs to be located and tested

**Comment by rparnas** [comment]
Is this used on the in-game pocket computer in Forest? A click hit "Home" when I expected it to hit "Power".

(works on retail)

![home](https://user-images.githubusercontent.com/1754130/171971190-c3e3375d-a661-41cc-b39b-92e82f7ac954.png)

**Comment by elasota** [comment]
No, the boundary detection modifier is used to fire messages when something moves outside of another element's bounds.  I believe there are some uses of it in the game, but need to check the disassembly and identify them.

The journal click detection bug is caused by #104.

**Comment by elasota** [comment]
The boundary detection modifier is used by the pong minigame in Bureau.  Currently it's not working correctly, which is causing the balls to fly out of bounds.
